package com.datamation.swdsfa.model;

public class ReceiptDet {
	
	private String FPRECDET_ID; 
	private String FPRECDET_REFNO ;
	private String FPRECDET_REFNO1 ;
	private String FPRECDET_REFNO2 ;
	private String FPRECDET_SALEREFNO ;
	private String FPRECDET_MANUREF ;
	private String FPRECDET_TXNTYPE ;
	private String FPRECDET_TXNDATE ;
	private String FPRECDET_DTXNDATE ;
	private String FPRECDET_DTXNTYPE;
	private String FPRECDET_DCURCODE ;
	private String FPRECDET_DCURRATE ;
	private String FPRECDET_OCURRATE;
	private String FPRECDET_REPCODE ;
	private String FPRECDET_AMT ;
	private String FPRECDET_BAMT ;
	private String FPRECDET_ALOAMT ;
	private String FPRECDET_OVPAYAMT ;
	private String FPRECDET_OVPAYBAL ;
	private String FPRECDET_RECORDID ;
	private String FPRECDET_TIMESTAMP ;
	private String FPRECDET_DEBCODE ;
	private String FPRECDET_ISDELETE ;
	private String FPRECDET_REMARK ;
	
	
	public String getFPRECDET_ISDELETE() {
		return FPRECDET_ISDELETE;
	}
	public void setFPRECDET_ISDELETE(String fPRECDET_ISDELETE) {
		FPRECDET_ISDELETE = fPRECDET_ISDELETE;
	}
	public String getFPRECDET_REFNO2() {
		return FPRECDET_REFNO2;
	}
	public void setFPRECDET_REFNO2(String fPRECDET_REFNO2) {
		FPRECDET_REFNO2 = fPRECDET_REFNO2;
	}
	public String getFPRECDET_DEBCODE() {
		return FPRECDET_DEBCODE;
	}
	public void setFPRECDET_DEBCODE(String fPRECDET_DEBCODE) {
		FPRECDET_DEBCODE = fPRECDET_DEBCODE;
	}
	public String getFPRECDET_ID() {
		return FPRECDET_ID;
	}
	public void setFPRECDET_ID(String fPRECDET_ID) {
		FPRECDET_ID = fPRECDET_ID;
	}
	public String getFPRECDET_REFNO() {
		return FPRECDET_REFNO;
	}
	public void setFPRECDET_REFNO(String fPRECDET_REFNO) {
		FPRECDET_REFNO = fPRECDET_REFNO;
	}
	public String getFPRECDET_REFNO1() {
		return FPRECDET_REFNO1;
	}
	public void setFPRECDET_REFNO1(String fPRECDET_REFNO1) {
		FPRECDET_REFNO1 = fPRECDET_REFNO1;
	}
	public String getFPRECDET_SALEREFNO() {
		return FPRECDET_SALEREFNO;
	}
	public void setFPRECDET_SALEREFNO(String fPRECDET_SALEREFNO) {
		FPRECDET_SALEREFNO = fPRECDET_SALEREFNO;
	}
	public String getFPRECDET_MANUREF() {
		return FPRECDET_MANUREF;
	}
	public void setFPRECDET_MANUREF(String fPRECDET_MANUREF) {
		FPRECDET_MANUREF = fPRECDET_MANUREF;
	}
	public String getFPRECDET_TXNTYPE() {
		return FPRECDET_TXNTYPE;
	}
	public void setFPRECDET_TXNTYPE(String fPRECDET_TXNTYPE) {
		FPRECDET_TXNTYPE = fPRECDET_TXNTYPE;
	}
	public String getFPRECDET_TXNDATE() {
		return FPRECDET_TXNDATE;
	}
	public void setFPRECDET_TXNDATE(String fPRECDET_TXNDATE) {
		FPRECDET_TXNDATE = fPRECDET_TXNDATE;
	}
	public String getFPRECDET_DTXNDATE() {
		return FPRECDET_DTXNDATE;
	}
	public void setFPRECDET_DTXNDATE(String fPRECDET_DTXNDATE) {
		FPRECDET_DTXNDATE = fPRECDET_DTXNDATE;
	}
	public String getFPRECDET_DTXNTYPE() {
		return FPRECDET_DTXNTYPE;
	}
	public void setFPRECDET_DTXNTYPE(String fPRECDET_DTXNTYPE) {
		FPRECDET_DTXNTYPE = fPRECDET_DTXNTYPE;
	}
	public String getFPRECDET_DCURCODE() {
		return FPRECDET_DCURCODE;
	}
	public void setFPRECDET_DCURCODE(String fPRECDET_DCURCODE) {
		FPRECDET_DCURCODE = fPRECDET_DCURCODE;
	}
	public String getFPRECDET_DCURRATE() {
		return FPRECDET_DCURRATE;
	}
	public void setFPRECDET_DCURRATE(String fPRECDET_DCURRATE) {
		FPRECDET_DCURRATE = fPRECDET_DCURRATE;
	}
	public String getFPRECDET_OCURRATE() {
		return FPRECDET_OCURRATE;
	}
	public void setFPRECDET_OCURRATE(String fPRECDET_OCURRATE) {
		FPRECDET_OCURRATE = fPRECDET_OCURRATE;
	}
	public String getFPRECDET_REPCODE() {
		return FPRECDET_REPCODE;
	}
	public void setFPRECDET_REPCODE(String fPRECDET_REPCODE) {
		FPRECDET_REPCODE = fPRECDET_REPCODE;
	}
	public String getFPRECDET_AMT() {
		return FPRECDET_AMT;
	}
	public void setFPRECDET_AMT(String fPRECDET_AMT) {
		FPRECDET_AMT = fPRECDET_AMT;
	}
	public String getFPRECDET_BAMT() {
		return FPRECDET_BAMT;
	}
	public void setFPRECDET_BAMT(String fPRECDET_BAMT) {
		FPRECDET_BAMT = fPRECDET_BAMT;
	}
	public String getFPRECDET_ALOAMT() {
		return FPRECDET_ALOAMT;
	}
	public void setFPRECDET_ALOAMT(String fPRECDET_ALOAMT) {
		FPRECDET_ALOAMT = fPRECDET_ALOAMT;
	}
	public String getFPRECDET_OVPAYAMT() {
		return FPRECDET_OVPAYAMT;
	}
	public void setFPRECDET_OVPAYAMT(String fPRECDET_OVPAYAMT) {
		FPRECDET_OVPAYAMT = fPRECDET_OVPAYAMT;
	}
	public String getFPRECDET_OVPAYBAL() {
		return FPRECDET_OVPAYBAL;
	}
	public void setFPRECDET_OVPAYBAL(String fPRECDET_OVPAYBAL) {
		FPRECDET_OVPAYBAL = fPRECDET_OVPAYBAL;
	}
	public String getFPRECDET_RECORDID() {
		return FPRECDET_RECORDID;
	}
	public void setFPRECDET_RECORDID(String fPRECDET_RECORDID) {
		FPRECDET_RECORDID = fPRECDET_RECORDID;
	}
	public String getFPRECDET_TIMESTAMP() {
		return FPRECDET_TIMESTAMP;
	}
	public void setFPRECDET_TIMESTAMP(String fPRECDET_TIMESTAMP) {
		FPRECDET_TIMESTAMP = fPRECDET_TIMESTAMP;
	}
	public String getFPRECDET_REMARK() {
		return FPRECDET_REMARK;
	}
	public void setFPRECDET_REMARK(String fPRECDET_REMARK) {
		FPRECDET_REMARK = fPRECDET_REMARK;
	}
	
	

}
